# Generated by Django 4.0.3 on 2022-03-24 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnChainTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("btc", models.FloatField()),
                ("satoshis", models.IntegerField(blank=True, null=True)),
                ("receiving_address", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("priority_level", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("bitnob_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LightningTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("btc", models.FloatField()),
                ("satoshis", models.IntegerField(blank=True, null=True)),
                ("lightening_address", models.CharField(max_length=100)),
                ("reference", models.CharField(max_length=100)),
                ("priority_level", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("bitnob_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
