# Generated by Django 4.0.3 on 2022-03-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightningtransaction',
            name='lightening_address',
        ),
        migrations.RemoveField(
            model_name='lightningtransaction',
            name='priority_level',
        ),
    ]
