# Generated by Django 4.0.3 on 2022-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_lightningtransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningtransaction',
            name='is_receciever_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onchaintransaction',
            name='is_receciever_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
