# Generated by Django 4.0.3 on 2022-03-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_lightningtransaction_is_receciever_confirmed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightningtransaction',
            old_name='is_receciever_confirmed',
            new_name='is_receiver_confirmed',
        ),
        migrations.RenameField(
            model_name='onchaintransaction',
            old_name='is_receciever_confirmed',
            new_name='is_receiver_confirmed',
        ),
    ]
