# Generated by Django 4.0.3 on 2022-03-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_is_receciever_confirmed_lightningtransaction_is_receiver_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onchaintransaction',
            name='is_receiver_confirmed',
        ),
    ]
