# Generated by Django 4.0.3 on 2022-03-25 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnChainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('btc', models.FloatField()),
                ('satoshis', models.IntegerField(blank=True, null=True)),
                ('receiving_address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('priority_level', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('bitnob_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LightningTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('btc', models.FloatField()),
                ('satoshis', models.IntegerField(blank=True, null=True)),
                ('lightening_address', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('priority_level', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('bitnob_id', models.CharField(max_length=100)),
                ('payment_request', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightening_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightening_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
