# Generated by Django 4.0.3 on 2022-03-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightningtransaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='onchaintransaction',
            name='receiver',
        ),
    ]
