# Generated by Django 4.0.3 on 2022-03-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_lightningtransaction_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightningtransaction',
            old_name='payment_request',
            new_name='lnAddress',
        ),
        migrations.RemoveField(
            model_name='lightningtransaction',
            name='reference',
        ),
    ]
