# Generated by Django 4.0.3 on 2022-03-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_payment_request_lightningtransaction_lnaddress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnchainAddress',
        ),
    ]
