# Generated by Django 4.0.3 on 2022-03-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_onchaintransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningtransaction',
            name='reference',
            field=models.CharField(default='38dec026-6112-40a0-a3a0-66846bd8fd05', max_length=100),
        ),
    ]
