# Generated by Django 4.0.3 on 2022-03-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_lightningtransaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightningtransaction',
            name='reference',
            field=models.CharField(default='1aba9e77-9401-4012-91dd-b4bf772c56d0', max_length=100),
        ),
    ]
